### ISSUE TITLE
let seems like pointless verbosity

### ISSUE THREAD

**Issue by cowens** [gregsexton/VimCalc#2]
The `let` preceding a variable assignment seems pointless.  You can tell you have an assignment by the usage of an assignment operator.

**Comment by gregsexton** [comment]
Agreed, the `let` in an assignment isn't necessary and wouldn't cause ambiguity with the current grammar. I chose to use it as it felt more 'mathematical'. I'll make it optional before the next release.

**Comment by gregsexton** [comment]
let in assignments is now optional as of commit 29b02b48.

**Comment by cowens** [comment]
Thanks, that works well.
