### ISSUE TITLE
Does not run in Gvim in Windows

### ISSUE THREAD

**Issue by zakneutron** [gregsexton/VimCalc#4]
Hi - I don't know if you want "bugs" putting here?

I have installed VimCalc by way of vim-pathogen.
I have placed the zipped contents of vim-calc into the bundle folder at:

C:\Program Files\Vim\vimfiles\bundle\plugin\vimcalc.vim

Restarted Gvim
Type :Calc in command mode
E492: Not an editor command

I have Python 2.6 and 3.1 installed in the C: root folder

Any thoughts?

**Comment by roidrage** [comment]
You need to put a directory unterneath bundle, e.g. vimcalc, and put all the files in there. That's the pathogen way so it's easier to manage plugins separately.

**Comment by zakneutron** [comment]
Thanks matt - I have got a bit further:

:Calc now brings up:

"VCalc requires the Python interface to be installed"

?

**Comment by roidrage** [comment]
That could turn out to be a bigger problem. No idea if there's a Windows build available that includes Python support.

**Comment by zakneutron** [comment]
I think then I may not have this functionality at work then (Windows ONLY). Can't find details of how to enable Gvim to interface with Python on Windows.
Will be OK at home - Ubuntu/Fedora....

**Comment by gregsexton** [comment]
Hi,

I use VimCalc at work (also Windows only). You need to have a version of Vim with Python support compiled in. This is easy to check by running the :version command in Vim. You're looking for '+python/dyn'. I'm fairly sure the official self-extracting download of Vim has Python support. 

Once you have this it is then a case of getting _exactly_ the right version of python installed on your machine. Further in the version listing you should see something that looks like: -DDYNAMIC_PYTHON_DLL=\"python27.dll\". This tells you that this version of Vim is linked against Python version 2.7 in this example. If you install the correct version in your root C:\ folder it should work.

After getting a Python enabled Vim and the right version of Python installed. It should be as simple as restarting Vim and running the :Calc command. Everything should just work. If you have any more problems please post back here. Be sure to record any error messages you receive.

Thanks,

Greg

**Comment by zakneutron** [comment]
Thanks Greg

I just needed to install windows python 2.7.

Works a treat.

Thanks for all your work to produce this.

zak
