### ISSUE TITLE
Error when running vim

### ISSUE THREAD

**Issue by ghost** [gregsexton/VimCalc#5]
Whenever I try to run vim with `vimcalc` installed, I get the following error:

```
Error detected while processing /Users/mark/.vim/plugin/vimcalc.vim:
line   34:
E121: Undefined variable: g:VCalc_Prompt
E15: Invalid expression: g:VCalc_Prompt != ''
```

**Comment by ghost** [comment]
Nevermind, I found out that the reason was that I accidentially copied the contents of `syntax/` into `~/.vim/plugin/`

**Comment by gregsexton** [comment]
Glad you resolved the issue.
