### ISSUE TITLE
Trailing decimal points are syntax errors

### ISSUE THREAD

**Issue by RhysU** [gregsexton/VimCalc#9]
Observe:

```
> 1./3
Syntax error: ./3
```

`1.` should behave as `1.0`

**Comment by gregsexton** [comment]
I don't agree. `1.` is not a number and should not be tokenized as one.

**Comment by RhysU** [comment]
While I appreciate the purity of your opinion, I assure you the `1.` floating point literals are very real--

```
$ gdb
(gdb) whatis 1
type = int
(gdb) whatis 1.
type = double
```

Most (all?) languages derived from C and many scripting languages accept them:

```
$ python
>>> type(1)
<type 'int'>
>>> type(1.)
<type 'float'>
```

Off the top of my head, that includes Awk, BC, C, C++, Common Lisp, D, Go, and Java.  Some of us are in the habit of typing them to avoid accidentally performing integer division.  If you've philosophical concerns against them, simply don't use them yourself.
